### Data preprocessing with Scikit-learn

* Preprocessing :
- Data Preprocessing is a technique that is used to convert raw data into a clean dataset

### Data Preprocessing steps

* Loading data (reading files)
* Exploring data(Summarizing ,statistics etc)
* Cleaning data ( handling missing values)
* Transforming data(Scaling,feature engineering etc..)
    * will learn data preprocessing technique with scikit-learn, one of the most popular framework used for Datascience
    * The scikit-learnn library includes tools for data preprocessing and data mining.
    * import sklearn
    * provides machine learning algorithms : classification,regression,clustering,model validation etc
    * Scikitlearn built on Numpy,Scipy and Matplotlib
    

### Data imputation

* Used to deal with missing values)
* Data imputation is a method for retaining majority of the dataset's data and information by substituting missing data with a different value.
* There are many different methods for data imputation
    * Using the mean value
    * Using the median value
    * Using the Most frequent value(mode)
    * Filling missing values with a constant
    

In [1]:
from sklearn.impute import SimpleImputer

In [4]:
import pandas as pd
import numpy as np
di={"a":pd.Series([10,20,30,np.nan,50],index=[1,2,3,4,5]),
    "b":pd.Series([11,24,39,24],index=[1,3,4,5]),
    "c":pd.Series([19,55,65,65],index=[1,2,3,4])
   }
df=pd.DataFrame(di)
df

a     b     c
1  10.0  11.0  19.0
2  20.0   NaN  55.0
3  30.0  24.0  65.0
4   NaN  39.0  65.0
5  50.0  24.0   NaN

*  fit_transform() from sklearn , preprocessing class is used to preprocess the for model training
* fit() - calculates various required parameters
* transform() - applies the calculated parameters to standardize the data
* fit_transform()- fit the data into a model and transform it into a form that is more suitable for model in a single step. This saves us time .

In [5]:
si=SimpleImputer(strategy="median")
si.fit_transform(df)

array([[10., 11., 19.],
       [20., 24., 55.],
       [30., 24., 65.],
       [25., 39., 65.],
       [50., 24., 60.]])

In [7]:
df.median()

a    25.0
b    24.0
c    60.0
dtype: float64

In [8]:
si=SimpleImputer(strategy="mean")
si.fit_transform(df)

array([[10. , 11. , 19. ],
       [20. , 24.5, 55. ],
       [30. , 24. , 65. ],
       [27.5, 39. , 65. ],
       [50. , 24. , 51. ]])

In [9]:
df.mean()

a    27.5
b    24.5
c    51.0
dtype: float64

In [11]:
si=SimpleImputer(strategy="most_frequent")
si.fit_transform(df)

C:\Users\meena\anaconda3\lib\site-packages\sklearn\impute\_base.py:49: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(array)


array([[10., 11., 19.],
       [20., 24., 55.],
       [30., 24., 65.],
       [10., 39., 65.],
       [50., 24., 65.]])

In [12]:
si=SimpleImputer(strategy="constant",fill_value=-1)
si.fit_transform(df)

array([[10., 11., 19.],
       [20., -1., 55.],
       [30., 24., 65.],
       [-1., 39., 65.],
       [50., 24., -1.]])

### Task

* Load titanic dataset
* clean data by using simpleImputer