In [1]:
import numpy as np

### linspace

* returns no of spaces evenly w.r.t to intervals
* similar to arange(), instead of step it uses sample number

In [2]:
a=np.linspace(1,20,4)
print(a)
print(type(a))

[ 1.          7.33333333 13.66666667 20.        ]
<class 'numpy.ndarray'>


### Array Initialization

* ones() returns a new array of given shape and type,with ones
* bydefault datatype float

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.ones(10,int)   # int

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
b=np.ones([2,2],np.int)
b

C:\Users\meena\AppData\Local\Temp\ipykernel_4544\130575635.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b=np.ones([2,2],np.int)


array([[1, 1],
       [1, 1]])

In [11]:
c=np.ones((3,2,1))
c

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [12]:
c.ndim

3

In [13]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [17]:
b=np.full([2,2],45)  # returns 2*2 array filled with value 45
b

array([[45, 45],
       [45, 45]])

In [18]:
np.empty(9)  # random values

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 7.35169681e-321, 3.11525958e-307, 1.24610723e-306,
       0.00000000e+000])

In [19]:
np.empty([2,2])

array([[0., 0.],
       [0., 0.]])

In [20]:
np.empty(15,np.complex)

C:\Users\meena\AppData\Local\Temp\ipykernel_4544\2740599895.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.empty(15,np.complex)


array([1.07522288e-311+1.07522066e-311j, 0.00000000e+000+0.00000000e+000j,
       7.56587583e-307+1.16097020e-028j, 1.26087994e-076+2.04380495e-028j,
       8.59813075e-067+1.04917183e-153j, 5.23081515e-143+8.37699872e+169j,
       4.01520706e-057+1.82961254e+184j, 9.42395448e-047+1.70098498e+256j,
       5.49109388e-143+1.06396443e+224j, 3.96041428e+246+1.16318408e-028j,
       2.63352810e-052+4.95592743e-062j, 1.33892789e-075+1.72213685e+184j,
       1.01848862e+248+1.16096643e-028j, 9.80058441e+252+7.50189709e+247j,
       1.14484251e+243+2.59903827e-144j])

### eye() - create 2D array with 1's on diagonal and 0's elsewhere

In [21]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.eye(3,k=1)   # k=1 upper diagonal

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [24]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [25]:
# 3,4,5 as diagonal values

np.diag([3,4,5])


array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [26]:
## array elements accessing - 1D

a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [27]:
print(a[0])

10


In [28]:
print(a[1])

20


In [29]:
print(a[0]+a[1])

30


In [30]:
## 2D array

l1=[1,2,3]
l2=[4,5,6]
b=np.array([l1,l2])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
b.ndim

2

In [32]:
# to access 2D array elements

b[1,0]   # row index,col index

4

In [33]:
b[1][0]

4

In [34]:
b[0,2]

3

In [39]:
# 3D array

c=np.array([ [[10,20],[30,40]], [[50,60],[90,87]]])
c

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [90, 87]]])

In [36]:
c.ndim

3

In [37]:
c[0]

array([[10, 20],
       [30, 40]])

In [38]:
c[1]

array([[50, 60],
       [90, 87]])

In [40]:
c[1,1,0]

90

In [41]:
# slicing in arrays

a

array([10, 20, 30, 40, 50])

In [42]:
a[1:3]   #20,30

array([20, 30])

In [43]:
# 10,30,50

a[::2]

array([10, 30, 50])

In [44]:
# 20,40

a[1::2]

array([20, 40])

In [45]:
# reverse of an array

a[::-1]

array([50, 40, 30, 20, 10])

In [47]:
# create an 2d array with array values as 3

a=np.full([2,2],3)

In [48]:
a

array([[3, 3],
       [3, 3]])

In [50]:
a[1]=5

In [51]:
a

array([[3, 3],
       [5, 5]])

In [52]:
a[1][1]=8

In [53]:
a

array([[3, 3],
       [5, 8]])

## Array manipulation

In [56]:
a

array([[3, 3],
       [5, 8]])

In [55]:
a.reshape(2,1,2)  #converting 2D into 3D

array([[[3, 3]],

       [[5, 8]]])

In [57]:
# random

np.random.random()   # gives random float b/w o to 1

0.06246710092514318

In [60]:
np.random.randint(780)  # returns a random value in the given range

218

In [61]:
np.random.randint(20,60,5)  # range,size

array([31, 45, 36, 57, 35])

In [62]:
np.random.randint(2,10,(2,4))  # range, shape

array([[9, 9, 3, 7],
       [2, 8, 2, 8]])

## fancy indexing or boolean indexing

In [63]:
a=np.random.randint(1,100,15)
a

array([41, 86, 58, 56, 47, 41, 50, 44, 49, 15, 43, 17, 74, 95, 35])

In [64]:
a>40

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False])

In [65]:
a[a>40]  # boolean indexing

array([41, 86, 58, 56, 47, 41, 50, 44, 49, 43, 74, 95])

In [66]:
(a>40).sum()

12

In [68]:
a[(a>70) & (a<80)]=200   # changing original array elements

In [69]:
a

array([ 41,  86,  58,  56,  47,  41,  50,  44,  49,  15,  43,  17, 200,
        95,  35])

In [70]:
a=np.arange(16)

In [71]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
a.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [74]:
a.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [75]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [77]:
a.reshape(4,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
a.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### vectorization

- used to implement array operations without using loops

In [79]:
def grt(a,b):
    if a>b:
        return a
    else:
        return b

In [80]:
grt(65,43)

65

In [81]:
grt([90,8,70],[78,76,67])

[90, 8, 70]

In [82]:
vgrt=np.vectorize(grt)
vgrt([90,8,70],[78,76,67])

array([90, 76, 70])

In [83]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [84]:
b=np.identity(2)
b

array([[1., 0.],
       [0., 1.]])

In [85]:
a+b

array([[2., 2.],
       [3., 5.]])

In [87]:
a*b  #normal multiplication

array([[1., 0.],
       [0., 4.]])

In [88]:
np.dot(a,b)  # matrix multiplication

array([[1., 2.],
       [3., 4.]])