### Numpy

* Numpy - numerical python
* It is an open source python library
* numpy provides high level functioning tools to work with arrays
* Using numpy we can perform mathematical and logical operations on arrays
* It also has functions in domain of linear algebra,fourier transforms and matrices

### Advantages of using numpy arrays over python lists:
* consumes less memory
* fast as compared with the python lists
* convinient to use

In [2]:
l=[1,2,3,4,5]   # 8

In [4]:
l+8   # element wise operation is not possible in list

TypeError: can only concatenate list (not "int") to list

In [6]:
import numpy as np

In [7]:
# creating 1D array

a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
type(a)

numpy.ndarray

In [9]:
a+8

array([ 9, 10, 11, 12, 13])

In [14]:
print(a.ndim)   # no of dimensions
print(a.dtype)  #data type of items
print(a.shape) #shape
print(a.size)  #no of elements inside an array
print(a.itemsize)  #each item size

1
int32
(5,)
5
4


In [57]:
b=np.array([[1,2,3],[6,7,8]])
print(b.shape)
print(b)

(2, 3)
[[1 2 3]
 [6 7 8]]


In [15]:
a1=np.array([12,34,45,67],dtype="complex")
a1

array([12.+0.j, 34.+0.j, 45.+0.j, 67.+0.j])

In [16]:
a2=np.array([11,21,32],ndmin=2)
a2

array([[11, 21, 32]])

In [17]:
a2.ndim

2

In [18]:
b=np.array([10,89,76,45,34])
b

array([10, 89, 76, 45, 34])

In [19]:
# sum of array elements

b.sum()

254

In [21]:
# maximum value of array elements
b.max()

89

In [23]:
## minimum value of array elements
b.min()

10

In [25]:
# index of min array element

b.argmin()

0

In [26]:
# index of max array element
b.argmax()

1

In [27]:
c=np.array([9,8,80,67],np.int8)
c

array([ 9,  8, 80, 67], dtype=int8)

In [29]:
d=np.array([9,8,80,67,512],np.int8)   
d

array([ 9,  8, 80, 67,  0], dtype=int8)

In [30]:
2**8

256

In [31]:
np.array([90,78,56,255],np.int8)

array([90, 78, 56, -1], dtype=int8)

In [32]:
np.array([90,78,56,127],np.int8)

array([ 90,  78,  56, 127], dtype=int8)

In [36]:
a=np.array([89,87,78.9])
print(a)
print(a.dtype)

[89.  87.  78.9]
float64


In [40]:
a1=np.array([1,2,3],dtype="float")   # various ways to create array with float
a2=np.array([1,2,3],np.float)
a3=np.array([1,2,3],float)

print(a1)
print(a2)
print(a3)

[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]


C:\Users\meena\AppData\Local\Temp\ipykernel_7308\1572802628.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a2=np.array([1,2,3],np.float)


### range() and arange()
* main difference between these two is range() is a built in function in python, where as arange is belongs to numpy

In [41]:
b=np.array(range(1,100))
print(b)
print(type(b))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
<class 'numpy.ndarray'>


In [43]:
c=np.arange(1,100)
print(c)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
c=np.arange(1,100,2)
print(c)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [45]:
c+5

array([  6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,
        32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,
        58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
        84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104])

In [50]:
a=np.arange(25)
print(a)
print(a.ndim)

b=a.reshape(5,5)   # reshaping 1D array into 2D
print(b)
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
1
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
2


In [52]:
for i in a:
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 